# Generated by Django 4.1.3 on 2023-03-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priyanka',
            name='original_url',
            field=models.URLField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='priyanka',
            name='short_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
